export default {
  FARMERS_COST: 30,
  FARMERS_COST_INCREASE: 1.2,
  SHOVELS_COST: 10,
  SHOVELS_COST_INCREASE: 1.5,
  SCYTHE_COST: 100,
  SCYTHE_COST_INCREASE: 10,
  SCYTHE_FARMERS_INCREASE: 0.2,
  HORSE_COST: 100,
  HORSE_COST_INCREASE: 5,
  HORSE_BONUS: 0.01,
  GRAVE_DIGGER_COST: 100,
  GRAVE_DIGGER_COST_INCREASE: 1.5,
};
