export default {
  MINERS_COST: 30,
  MINERS_COST_INCREASE: 1.2,
  SHOVELS_COST: 10,
  SHOVELS_COST_INCREASE: 1.5,
  PICKAXE_COST: 100,
  PICKAXE_COST_INCREASE: 10,
  PICKAXE_MINERS_INCREASE: 0.2,
  SMART_MINER_COST: 100,
  SMART_MINER_COST_INCREASE: 5,
  SMART_MINER_BONUS: 0.01,
  GRAVE_DIGGER_COST: 100,
  GRAVE_DIGGER_COST_INCREASE: 1.5,
};
