export default {
  MINERS_COST: 30,
  MINERS_COST_INCREASE: 1.75,
  SHOVELS_COST: 10,
  SHOVELS_COST_INCREASE: 2,
  PICKAXE_COST: 100,
  PICKAXE_COST_INCREASE: 10,
  PICKAXE_MINERS_INCREASE: 0.1,
  SMART_MINER_COST: 500,
  SMART_MINER_COST_INCREASE: 10,
  SMART_MINER_BONUS: 0.01,
};
